let button = document.querySelector("button");
let changeDiv = document.querySelector("#ai-answer");
let removeBubble = document.querySelector(".bubble-container");
removeBubble.style.display = "block";

let key = "58f070a40818f233c2b84bto089b72e4";

var msg = new SpeechSynthesisUtterance();
const voices = speechSynthesis.getVoices();
msg.lang = "en-GB";


function showAnswer(response) {
	let story = response.data.answer;

	let styles = {
		fontFamily:  "Playwrite AR",
		padding: "15px",
		margin: "15px",
		border: "1px solid red",
		borderRadius: "20px",
		backgroundColor: "lightyellow",
		color: "darkred",
	};

    let extraSentence = '<span style="color: purple; font-family: Roboto, sans-serif; padding-top: 2rem;"> - Generated by Storyella AI (Shecodes AI).</span>';

    Object.assign(changeDiv.style, styles);

    let typewrite = new Typewriter(changeDiv, {
        strings: story + "<br>" + extraSentence,
        loop: false,
        cursor: null,
        delay: 45,
        autoStart: true,
    });

	msg.text = story;
	msg.rate = 0.9;
	window.speechSynthesis.speak(msg);
}

function pretext()
{
	let waitingStory = "Generating a story for you, please wait...";

	let styles = {
		padding: "15px",
		margin: "15px",
		border: "1px solid red",
		borderRadius: "20px",
		backgroundColor: "lightyellow",
		color: "purple",
	};

    Object.assign(changeDiv.style, styles);

    let typewrite = new Typewriter(changeDiv, {
        strings: waitingStory,
        loop: false,
        cursor: null,
        delay: 6,
        autoStart: true,
    });

	msg.text = waitingStory;
	window.speechSynthesis.speak(msg);
}

document.querySelector("#prompt-form").addEventListener("submit", function (event) {
	event.preventDefault();

	let userPrompt = document.querySelector("#user-prompt").value;
	let justSigns = userPrompt.replace(/[^\W_]+/g, "");
	let justSpaces = " ".repeat(userPrompt.length);

	if (userPrompt === "" || userPrompt === justSpaces) {
		alert("Please enter a prompt!");
		window.location.reload();
		return;
	}

	let vowels = userPrompt.match(/[aeiouAEIOU]/g) || [];
	let consonants = userPrompt.match(/[bcdfghjklmnpqrstvwxyzBCDFGHJKLMNPQRSTVWXYZ]/g) || [];
		if (consonants.length / userPrompt.length > 0.7 || vowels.length === 0 || userPrompt === justSigns) {
			alert("Please enter a more meaningful prompt!");
			window.location.reload();
			return;
		}

	if (userPrompt.length > 100) {
		alert("Please enter a prompt with max 100 characters!");
		window.location.reload();
		return;
	}

	let question = {
		prompt: userPrompt,
		context: "Please make it short, maximun 3 sentences, if the prompt is a number invent a story around it, if it is exactly the number 42 tell a story about how is the answer of life (The hitchhiker's guide to the galaxy), otherwise create a story about the prompt.",
	};

	const UNSPLASH_ACCESS_KEY = '6DnKSAKQHcbimFiIdeXf-hmrDbHCYiqD3zNn7ucHFcQ';

	fetch(`https://api.unsplash.com/photos/random?query=${userPrompt}&client_id=${UNSPLASH_ACCESS_KEY}`)
		.then(response => response.json())
		.then(photoData => {
			let container = document.querySelector("body");
			removeBubble.style.display = "none";
			container.style.backgroundImage = `url(${photoData.urls.regular})`;
			container.style.backgroundSize = "cover";
			container.style.backgroundPosition = "center";
			container.style.backgroundRepeat = "no-repeat";
		})
		.catch(error => console.error('Error fetching city image:', error));


	let apiUrl = `https://api.shecodes.io/ai/v1/generate?prompt=${encodeURIComponent(
		question.prompt
	)}&context=${encodeURIComponent(question.context)}&key=${key}`;


	pretext();
	axios.get(apiUrl).then(showAnswer);
});